---
- name: Add tomcat group
  group:
    name: tomcat
  tags:
    - install_tomcat

- name: Add "tomcat" user
  user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    createhome: no
    system: yes
  tags:
    - install_tomcat