---
- name: Check Apache (apache2) service status on Ubuntu
  shell:
    cmd: "systemctl status apache2 | grep Active"
  register: apache_status
  tags:
    - status

- name: Display Apache service status 
  debug:
    msg: "Status: {{ apache_status.stdout_lines | first }}"
  tags:
    - status



    