---
- name: Install Apache (httpd) on Ubuntu
  apt:
    name: apache2
    state: present
  become: true
  tags:
    - install

- name: Start and enable Apache service on Ubuntu
  service:
    name: apache2
    state: started
    enabled: true
  become: true
  tags:
    - install
    - start
  
- name: Stop Apache (apache2) service on Ubuntu
  systemd:
    name: apache2
    state: stopped
  become: true
  tags:
    - stop