---
- name: Podstawowy playbook z tagiem
  hosts: all
  gather_facts: no
  roles:
    - {role: my_role}
  tags:
    - tag1


  tasks:
    - name: 'task 1'
      include: task1_playbook.yml
      tags:
          - tag1



    # - name: main task
    #   debug:
    #     msg: "To jest main task."
    #   tags:
    #     - tag1