--- 
- name: Create Jenkins group
  become: true
  group:
    name: jenkins
    state: present

- name: Create Jenkins user
  become: true
  user:
    name: jenkins
    password: jenkins
    group: jenkins
    home: /home/jenkins
    state: present

# ======================

- name: Create Jenkins directories
  file:
    path: "{{ item }}"
    owner: jenkins
    group: jenkins
    mode: "0755"
    state: directory
  loop:
    - /opt/jenkins/caches
    - /opt/jenkins/config
    - /opt/jenkins/home
    - /opt/jenkins/lib
    - /opt/jenkins/userContent
  loop_control:
    loop_var: item

- name: Ensure that Jenkins secrets directory exists
  become: true
  file:
    path: /opt/jenkins/secrets
    owner: jenkins
    group: jenkins
    mode: "0700"
    state: directory

# ======================

- name: Install Java (OpenJDK)
  package:
    name: java-11-openjdk   # or java-1.8.0-openjdk
    state: present
  tags:
    - install_tomcat

- name: Check java_version
  shell:
    cmd: "java -version 2>&1 | grep \"openjdk version\""
  register: java_version
  ignore_errors: true 
  tags:
    - install_tomcat

- name: Display java_version
  debug:
    msg: "java_version: {{ java_version.stdout_lines | first }}"
  tags:
    - install_tomcat

# ======================

- name: Download Jenkins WAR file
  become: true
  ansible.builtin.get_url:
    url: "https://mirrors.jenkins.io/war-stable/{{ jenkins_version }}/jenkins.war"
    checksum: "sha256:https://mirrors.jenkins.io/war-stable/{{ jenkins_version }}/jenkins.war.sha256"
    dest: "{{ jenkins_war }}"
    timeout: "{{ jenkins_download_timeout }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"
  vars:
    jenkins_version: "2.319"
  retries: "{{ jenkins_download_retries }}"
  delay: "{{ jenkins_download_delay }}"
  register: download_jenkins_war_result
  until: download_jenkins_war_result is succeeded


# ======================




# ======================




# ======================






















