---
# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
# jenkins_version: "1.644"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

jenkins_prefer_lts: false

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
#jenkins_hostname: jenkins.mycompany.com
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

# Plugin list can use the plugin name, or a name/version dict.
jenkins_plugins:
  - name: pipeline-model-extensions
    version: "1.7.1"
  # - name: display-url-api
  #   version: "2.3.3"
  # - name: pipeline-graph-analysis
  #   version: "1.10"
  # - name: github
  #   version: "1.31.0"
  # - name: workflow-aggregator
  #   version: "2.6"
  # - name: jquery3-api
  #   version: "3.5.1-1"
  # - name: workflow-cps
  #   version: "2.82"
  # - name: workflow-cps-global-lib
  #   version: "2.17"
  # - name: durable-task
  #   version: "1.34"
  # - name: pipeline-model-definition
  #   version: "1.7.1"
  # - name: matrix-auth
  #   version: "2.6.2"
  # - name: pipeline-milestone-step
  #   version: "1.3.1"
  # - name: jquery-detached
  #   version: "1.2.1"
  # - name: workflow-api
  #   version: "2.40"
  # - name: ws-cleanup
  #   version: "0.38"
  # - name: gradle
  #   version: "1.36"
  # - name: momentjs
  #   version: "1.1.1"
  # - name: workflow-basic-steps
  #   version: "2.20"
  # - name: email-ext
  #   version: "2.75"
  # - name: ssh-slaves
  #   version: "1.31.2"
  # - name: resource-disposer
  #   version: "0.14"
  # - name: pam-auth
  #   version: "1.6"
  # - name: pipeline-build-step
  #   version: "2.13"
  # - name: pipeline-rest-api
  #   version: "2.14"
  # - name: pipeline-model-api
  #   version: "1.7.1"
  # - name: workflow-job
  #   version: "2.39"
  # - name: plugin-util-api
  #   version: "1.2.4"
  # - name: jsch
  #   version: "0.1.55.2"
  # - name: workflow-durable-task-step
  #   version: "2.36"
  # - name: bouncycastle-api
  #   version: "2.18"
  # - name: github-api
  #   version: "1.115"
  # - name: okhttp-api
  #   version: "3.14.9"
  # - name: command-launcher
  #   version: "1.4"
  # - name: branch-api
  #   version: "2.5.9"
  # - name: echarts-api
  #   version: "4.8.0-2"
  # - name: pipeline-github-lib
  #   version: "1.0"
  # - name: ace-editor
  #   version: "1.1"
  # - name: script-security
  #   version: "1.74"
  # - name: pipeline-stage-view
  #   version: "2.14"
  # - name: git
  #   version: "4.4.0"
  # - name: junit
  #   version: "1.32"
  # - name: github-branch-source
  #   version: "2.8.3"
  # - name: ant
  #   version: "1.11"
  # - name: token-macro
  #   version: "2.12"
  # - name: git-server
  #   version: "1.9"
  # - name: jdk-tool
  #   version: "1.4"
  # - name: lockable-resources
  #   version: "2.8"
  # - name: antisamy-markup-formatter
  #   version: "2.1"
  # - name: scm-api
  #   version: "2.6.3"
  # - name: git-client
  #   version: "3.4.2"
  # - name: timestamper
  #   version: "1.11.5"
  # - name: pipeline-stage-step
  #   version: "2.5"
  # - name: matrix-project
  #   version: "1.17"
  # - name: cloudbees-folder
  #   version: "6.14"
  # - name: trilead-api
  #   version: "1.0.8"
  # - name: mailer
  #   version: "1.32"
  # - name: pipeline-input-step
  #   version: "2.11"
  # - name: pipeline-stage-tags-metadata
  #   version: "1.7.1"
  # - name: handlebars
  #   version: "1.1.1"
  # - name: workflow-multibranch
  #   version: "2.22"
  # - name: workflow-support
  #   version: "3.5"
  # - name: workflow-scm-step
  #   version: "2.11"
  # - name: ldap
  #   version: "1.24"
  # - name: build-timeout
  #   version: "1.20"
  # - name: workflow-step-api
  #   version: "2.22"
  # - name: jackson2-api
  #   version: "2.11.2"
  # - name: ssh-credentials
  #   version: "1.18.1"
  # - name: credentials-binding
  #   version: "1.23"
  # - name: authentication-tokens
  #   version: "1.4"
  # - name: structs
  #   version: "1.20"
  # - name: credentials
  #   version: "2.3.12"
  # - name: kubernetes-credentials
  #   version: "0.7.0"
  # - name: apache-httpcomponents-client-4-api
  #   version: "4.5.10-2.0"
  # - name: plain-credentials
  #   version: "1.7"
  # - name: snakeyaml-api
  #   version: "1.26.4"
  # - name: terraform
  #   version: "1.0.10"
  # - name: job-dsl
  #   version: "1.77"
  # - name: configuration-as-code
  #   version: "1.43"
  # - name: kubernetes-client-api
  #   version: "4.9.2-2"
  # - name: azure-commons
  #   version: "1.0.4"
  # - name: kubernetes-cli
  #   version: "1.8.3"
  # - name: docker-commons
  #   version: "1.17"
  # - name: docker-workflow
  #   version: "1.24"
  # - name: azure-credentials
  #   version: "4.0.2"
  # - name: azure-cli
  #   version: "0.9"
  # - name: "google-login"
  #   version: "1.6"

jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: true
jenkins_updates_url: "https://updates.jenkins.io"

jenkins_admin_username: peter
jenkins_admin_password: peter
jenkins_admin_password_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"
#  - option: "JENKINS_ARGS"
#    value: "--httpListenAddress=127.0.0.1"

# If Jenkins is behind a proxy, configure this.
jenkins_proxy_host: ""
jenkins_proxy_port: ""
jenkins_proxy_noproxy:
  - "127.0.0.1"
  - "localhost"