---
- name: Install Jenkins
  hosts: jenkins_host
  gather_facts: no
  become: true
  remote_user: jenkins_agent
  roles:
    - role: install_all
  vars:
    __jenkins_repo_url: "https://pkg.jenkins.io/redhat{{ '-stable' if (jenkins_prefer_lts | bool) else '' }}/jenkins.repo"
    __jenkins_repo_key_url: "https://pkg.jenkins.io/redhat{{ '-stable' if (jenkins_prefer_lts | bool) else '' }}/jenkins.io.key"
    __jenkins_pkg_url: "https://pkg.jenkins.io/redhat"
    jenkins_init_file: "/etc/sysconfig/jenkins"
    jenkins_http_port_param: "JENKINS_PORT"
    jenkins_java_options_env_var: "JENKINS_JAVA_OPTIONS"
    ansible_os_family: 'RedHat'